import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

// Helper function to extract website ID based on domain or intent
async function resolveWebsite(targetInfo: string) {
  // Simplistic matching for MVP
  const { data, error } = await supabase
    .from('websites')
    .select('id, name, domain')
    .ilike('name', `%${targetInfo}%`)
    .limit(1)
    .single();

  if (error) return null;
  return data;
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { instruction, owner_id } = body;

    if (!instruction) {
      return NextResponse.json({ error: 'Instruction is required' }, { status: 400 });
    }

    // --- STEP 1: Understand Intent (Mocked for now) ---
    // In a full implementation, you would pass `instruction` to OpenAI/Gravity
    // to extract the target website, the role needed, and the breakdown of tasks.
    console.log(`[Orchestrator] Received instruction: "${instruction}"`);
    
    // Hardcoded logic for MVP demonstration: 
    // We assume the target website is 'GameHub' if not specified.
    const website = await resolveWebsite('GameHub');
    
    if (!website) {
      return NextResponse.json({ 
        message: 'Could not resolve target website. Make sure the website exists in the database.' 
      }, { status: 404 });
    }

    // --- STEP 2: Task Breakdown ---
    // Normally generated by AI. Here we create a single generic task to represent the delegation.
    const { data: taskData, error: taskError } = await supabase
      .from('tasks')
      .insert([
        {
          website_id: website.id,
          created_by: owner_id || 'owner_dashboard',
          title: 'Delegated Instruction',
          description: instruction,
          task_type: 'general',
          priority: 'high',
          status: 'queued',
          risk_level: 'low',
        }
      ])
      .select()
      .single();

    if (taskError) {
      throw taskError;
    }

    // --- STEP 3: Dispatch ---
    // Here we would ideally trigger a background worker (e.g. BullMQ, Celery, or Vercel Functions)
    // to pick up the task and assign it to the specific Agent (SEO, Marketing, etc.)
    console.log(`[Orchestrator] Task created successfully: ${taskData.id}`);

    return NextResponse.json({
      message: 'Instruction successfully received and parsed into tasks.',
      task_id: taskData.id,
      target_website: website.name,
      status: 'queued'
    });

  } catch (error: any) {
    console.error('[Orchestrator] Error processing request:', error.message);
    return NextResponse.json({ error: 'Internal Server Error', details: error.message }, { status: 500 });
  }
}
